[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 999_999
verbosity = 3
isolate = true

[fmt]
tab_width = 2
bracket_spacing = true
number_underscore = "thousands"

[rpc_endpoints]
optimism = "${OPTIMISM_RPC_URL}"
